server:
  port: 8080

spring:
  application:
    name: football-service
  profiles:
    active:
  datasource:
    url: jdbc:postgresql://localhost:5432/football_manager_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
